### ISSUE TITLE
Cookie Consent State Variable contains "|" instead of the selected consent value

### ISSUE THREAD

**Issue by tsterner** [cybotcorp/gtm-templates-cookiebot-variable#1]
Today, we added cookiebot via gtm according to https://support.cookiebot.com/hc/en-us/articles/360003793854

We did this for a couple of projects already without problems. 
However, today the Cookiebot Constent State Variable doesn't contain the selected consent value. 

This is the output in gtm debug mode showing the variable data of the cookie_consent_marketing event. The Cookiebot Consent State Variable should contain "marketing" but contains '\|'. See here:

_event | Custom Event | string | 'cookie_consent_marketing'
Cookie Consent State | Cookiebot Consent State | string | '\|'
Event |  Custom Event | string | 'cookie_consent_marketing'

Obviously, when configuring a trigger which checks the variable value, it doesn't fire.

**Comment by markusa86** [comment]
Same Problem here.

**Comment by danieljohannsen** [comment]
GTM policy around cookie access has apparently changed and now prevents the template from reading out values from the user's consent cookie if the template permission for 'cookieAccess' does not specify the exact cookie name, 'CookieConsent'. An update to the template has just now been committed, please allow 1-2 days for Google to release the update in GTM.

**Comment by danieljohannsen** [comment]
Google have now pushed the update to Google Tag Manager. Users must install the update and publish for the change to take effect. Click "View" at the top bar message "1 template update available" after logging in to GTM to begin the update.
